package com.hereams.neverland.constant

val SPRITES_SIZE = 128
val WAITING_PER_FRAME = 5
val DIRECTION_FORWARD = 0
val DIRECTION_RIGHT = 1
val DIRECTION_DOWN = 2
val DIRECTION_LEFT = 3
val MAX_MOVEMENT_SPRITES_SIZE = 12